steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-image:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app-image:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'app-pesquisa',
         '--image', 'gcr.io/$PROJECT_ID/app-image:$SHORT_SHA',
         '--region', 'us-east1',
         '--platform', 'managed',
         '--allow-unauthenticated']
substitutions:
  _REGION: 'us-east1'
images:
- 'gcr.io/$PROJECT_ID/app-image:$SHORT_SHA'